[package]
name = "account"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.16.1"

[dev-dependencies]
snforge_std = "0.57.0"
assert_macros = "2.16.1"

[[target.starknet-contract]]
sierra = true

[scripts]
test.workspace = true

[tool]
scarb.workspace = true
