// Builds fake Google letters (JWTs) and writes them as circuit inputs. Tests only.
// They are signed by a test key: the circuit accepts any RSA key, the contract checks it is Google's.
// RS256 is deterministic, so a rerun writes the same files.
//
// usage: make fixtures
//   Prover.toml            a valid letter, for `nargo execute` and the verifier proof
//   Prover.json            the same letter, for the web prover (web/)
//   src/tests/fixtures.nr  letters and constants for src/tests/

import crypto from "node:crypto";
import fs from "node:fs";
import { createRequire } from "node:module";
import { poseidon3, poseidon8 } from "poseidon-lite";

// noir-jwt 0.4.5's ESM build breaks in Node (extensionless imports), so load its CommonJS build
const { generateInputs } = createRequire(import.meta.url)("noir-jwt");

const GOOGLE_ISS = "https://accounts.google.com";
const CLIENT_ID =
  "123456789012-0123456789abcdef0123456789abcdef.apps.googleusercontent.com";
const SUB = "123456789012345678901"; // Google ids are 21 digits
const SESSION_PUBKEY = 1n; // any Field works: the circuit only hashes it
const SECRET = 2n;
const EXPIRY = 1800000000n; // Unix seconds (2027-01-15)
const SALT = 12345n; // the real one comes from the dev's server
const MAX_DATA_LENGTH = 1024; // same as in src/main.nr

// Same as `pack` in src/main.nr: 31 bytes per Field, padded with 0 bytes
const pack = (s: string, max: number) => {
  const bytes = Buffer.alloc(max);
  Buffer.from(s).copy(bytes);
  return Array.from({ length: max / 31 }, (_, i) =>
    BigInt("0x" + bytes.subarray(i * 31, (i + 1) * 31).toString("hex")),
  );
};

// Browser side: nonce = H(session key, expiry, secret), in decimal
const nonce = poseidon3([SESSION_PUBKEY, EXPIRY, SECRET]).toString();

// Google side: a test key shaped like Google's (2048 bits, exponent 65537)
const privateKey = crypto.createPrivateKey(
  fs.readFileSync(new URL("../fixtures/test_rsa_key.pem", import.meta.url)),
);
const publicKey = crypto.createPublicKey(privateKey);

// Google side: signs "header.payload" with RS256, like a real Google JWT
function sign(iss: string) {
  // Same claims, order and formats as Google's for scope "openid"
  const payload = {
    iss,
    azp: CLIENT_ID,
    aud: CLIENT_ID,
    sub: SUB,
    nonce,
    nbf: 1737641917,
    iat: 1737642217,
    exp: 1799999999, // 2027-01-15
    jti: "0123456789abcdef0123456789abcdef01234567", // keep last: login.nr tampers with it
  };
  const header = {
    alg: "RS256",
    kid: "0123456789abcdef0123456789abcdef01234567",
    typ: "JWT",
  };
  const b64 = (o: object) =>
    Buffer.from(JSON.stringify(o)).toString("base64url");
  const signedData = `${b64(header)}.${b64(payload)}`;
  const signature = crypto.sign("sha256", Buffer.from(signedData), privateKey);
  return `${signedData}.${signature.toString("base64url")}`;
}

// Expected circuit output, same layout as `identity_hash` in src/main.nr
const identityHash = poseidon8([
  ...pack(GOOGLE_ISS, 31),
  ...pack(CLIENT_ID, 93),
  BigInt(CLIENT_ID.length),
  ...pack(SUB, 31),
  BigInt(SUB.length),
  SALT,
]);

// Circuit inputs for one letter, computed by noir-jwt
const letter = (iss: string) =>
  generateInputs({
    jwt: sign(iss),
    pubkey: publicKey.export({ format: "jwk" }),
    maxSignedDataLength: MAX_DATA_LENGTH,
  });

const google = await letter(GOOGLE_ISS);
// signed correctly, but iss is not Google
const otherIss = await letter("http://test.com");

// Circuit inputs of the valid letter, as decimal strings
const str = (xs: unknown[]) => xs.map(String);
const inputs = {
  base64_decode_offset: String(google.base64_decode_offset),
  pubkey_modulus_limbs: str(google.pubkey_modulus_limbs),
  redc_params_limbs: str(google.redc_params_limbs),
  signature_limbs: str(google.signature_limbs),
  session_pubkey: String(SESSION_PUBKEY),
  expiry: String(EXPIRY),
  secret: String(SECRET),
  salt: String(SALT),
  data: { len: String(google.data.len), storage: str(google.data.storage) },
};

// Prover.toml: the valid letter, for nargo
const { data, ...top } = inputs;
const toml = (o: object) =>
  Object.entries(o).map(([k, v]) => `${k} = ${JSON.stringify(v)}`);
const prover = [
  ...toml(top),
  `return = "${identityHash}"`,
  "",
  "[data]",
  ...toml(data),
  "",
].join("\n");
fs.writeFileSync(new URL("../Prover.toml", import.meta.url), prover);

// Prover.json: the same letter, for the web prover
fs.writeFileSync(
  new URL("../Prover.json", import.meta.url),
  JSON.stringify(inputs),
);

// One `Letter` value, in Noir
const nrLetter = (
  name: string,
  l: typeof google,
) => `pub global ${name}: Letter = Letter {
    data: [${l.data.storage.join(", ")}],
    data_len: ${l.data.len},
    base64_decode_offset: ${l.base64_decode_offset},
    pubkey_modulus_limbs: [${l.pubkey_modulus_limbs.join(", ")}],
    redc_params_limbs: [${l.redc_params_limbs.join(", ")}],
    signature_limbs: [${l.signature_limbs.join(", ")}],
};
`;
const fixtures = `// Generated by scripts/fixture.ts (make fixtures), do not edit
use crate::MAX_DATA_LENGTH;

// A signed letter, as circuit inputs
pub struct Letter {
    pub data: [u8; MAX_DATA_LENGTH],
    pub data_len: u32,
    pub base64_decode_offset: u32,
    pub pubkey_modulus_limbs: [u128; 18],
    pub redc_params_limbs: [u128; 18],
    pub signature_limbs: [u128; 18],
}

pub global SESSION_PUBKEY: Field = ${SESSION_PUBKEY};
pub global SECRET: Field = ${SECRET};
pub global EXPIRY: u64 = ${EXPIRY};
pub global SALT: Field = ${SALT};
pub global IDENTITY_HASH: Field = ${identityHash};

${nrLetter("GOOGLE", google)}
${nrLetter("OTHER_ISS", otherIss)}`;
fs.writeFileSync(
  new URL("../src/tests/fixtures.nr", import.meta.url),
  fixtures,
);
